use serde::{Deserialize, Serialize};

/// Response for getting account details, [more info](https://docs.alpaca.markets/reference/getaccount-1)
#[derive(Clone, Deserialize, Debug, Eq, PartialEq, Serialize)]
#[allow(dead_code)]
pub struct GetAccountResp {
    id: String,
    account_number: Option<String>,
    status: String,
    currency: Option<String>,
    cash: Option<String>,
    portfolio_value: Option<String>,
    non_marginable_buying_power: Option<String>,
    accrued_fees: Option<String>,
    pending_transfer_in: Option<String>,
    pending_transfer_out: Option<String>,
    pattern_day_trader: Option<bool>,
    trade_suspended_by_user: Option<bool>,
    trading_blocked: Option<bool>,
    transfers_blocked: Option<bool>,
    account_blocked: Option<bool>,
    created_at: Option<chrono::DateTime<chrono::Utc>>,
    shorting_enabled: Option<bool>,
    long_market_value: Option<String>,
    short_market_value: Option<String>,
    equity: Option<String>,
    last_equity: Option<String>,
    multiplier: Option<String>,
    buying_power: Option<String>,
    initial_margin: Option<String>,
    maintenance_margin: Option<String>,
    sma: Option<String>,
    daytrade_count: Option<i32>,
    balance_asof: Option<String>,
    last_maintenance_margin: Option<String>,
    daytrading_buying_power: Option<String>,
    regt_buying_power: Option<String>,
    options_buying_power: Option<String>,
    options_approved_level: Option<i32>,
    options_trading_level: Option<i32>,
    intraday_adjustments: Option<String>,
    pending_reg_taf_fees: Option<String>,
}
